# Generated by Django 2.1 on 2022-04-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
